### PR TITLE
Week2 merge develop to main : basic main page

### PR DESCRIPTION
**Pull request by c20kyo1827**
管偉傑
[main page](http://54.66.119.114:3000/)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Your code will load first page two times when we search keyword.
3. There should be no spacing around the page.

未命名-2

**Comment by c20kyo1827** [comment]
Hi @cwpeng ,
I have fixed these errors.
Could you take a look?
Thanks a lot!

Best Regrads,
Allen

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code will load the same page multiple times if we scroll down and up quickly.


https://github.com/c20kyo1827/Taipei-one-day-tour/assets/6104683/ce7ac667-7237-4e39-86d1-1c7e33de958e

**Comment by c20kyo1827** [comment]
Hi @cwpeng ,
I have fixed this error.
Could you check the response?
Thanks a lot!

Best Regrads,
Allen

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by c20kyo1827** [comment]
Thanks a lot!

**Pull request merged**
