### PR TITLE
Week5 merge develop to main : booking page 

### PR DESCRIPTION
**Pull request by c20kyo1827**
管偉傑

[main page](http://54.66.119.114:3000/)
[attraction page](http://54.66.119.114:3000/attraction/17)
[booking page](http://54.66.119.114:3000/booking)

Could you review this week?
Thanks a lot!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We have to show singin dialog if user click 開始預訂行程 button without signing in.
2. Booking page can be better align with design.

**Comment by c20kyo1827** [comment]
Hi @cwpeng ,
Could you review this version?
Thank you!

Best Regards,
Allen

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by c20kyo1827** [comment]
@cwpeng 
Thank you for taking the time to review!

**Pull request merged**
