### PR TITLE
Week3 merge develop to main : attraction page

### PR DESCRIPTION
**Pull request by c20kyo1827**
管偉傑
[main page](http://54.66.119.114:3000/)
[attraction 10](http://54.66.119.114:3000/attraction/10)
[attraction 26](http://54.66.119.114:3000/attraction/26) => null mrt

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Separating lines are 1px height only.
2. There is no space between navigator bar and image slider in mobile layout.
3. Border style of 開始預約行程 button should align with design.

**Comment by c20kyo1827** [comment]
Hi @cwpeng,
Could you take a look at the fix?
Thanks a lot

Best Regards,
Allen

**Review by cwpeng — CHANGES_REQUESTED** [review]
There is no space between navigator bar and image slider in mobile layout.

54 66 119 114_3000_attraction_2

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by c20kyo1827** [comment]
Thank you very much for your kind assitance!

**Pull request merged**
