### PR TITLE
Week4 merge develop to main : sign-in/sign-up

### PR DESCRIPTION
**Pull request by c20kyo1827**
管偉傑
[main page](http://54.66.119.114:3000/)
[attraction 20](http://54.66.119.114:3000/attraction/20)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should reject repeated email in sign up procedure.
2. I cannot sign in by account that I just signed up.

**Comment by c20kyo1827** [comment]
Hi @cwpeng 
Could you check this version?
Thank you!

Best Regards,
Allen

**Review by cwpeng — CHANGES_REQUESTED** [review]
Close dialog after signing in successfully. We have to give enough UI feeback for user.

**Comment by c20kyo1827** [comment]
Hi @cwpeng
I have fixed the issue. Could you take a look?
Thank you!

Best Regards,
Allen

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by c20kyo1827** [comment]
Thank you for your kind review!

**Pull request merged**
